### ISSUE TITLE
Problem in VSS (Failover Cluster with 2 Hyper-V Server 2016 nodes and a SAN)

### ISSUE THREAD

**Issue by gskoc** [ColiseoSoftware/hypervbackup#12]
What could be the cause of this error? I can't back up some of the virtual machines on that CSVFS volume using hypervbackup v2.2.

This is a small script that runs the backup
set BCKPATH="\\node2\c$\ClusterStorage\Volume4\vmbackups"
HyperVBackup.exe --all --output %BCKPATH% --compressionlevel 2 1> last_output.log 2> last_error.log"

contents of last_error.log file are:

Error: The requested object was a duplicate.
   at Alphaleonis.Win32.Vss.VssBackupComponents.AddToSnapshotSet(String volumeName, Guid providerId)
   at HyperVBackUp.Engine.BackupManager.BackupSubset(IDictionary`2 vmNamesMapSubset, Options options)
   at HyperVBackUp.Engine.BackupManager.VssBackup(IEnumerable`1 vmNames, VmNameType nameType, Options options)
   at HyperVBackup.Console.Program.Main(String[] args)

**Comment by pablopioli** [comment]
I can look at this but I'll need that you perform some testing on your cluster.

The error indicates that it's trying to add a vm twice. So my first test will be to run the program without the --all switch, selecting only one virtual machine.

As I cannot be sure if this was a bug in the original code or was introduced by me I will try with the original program (http://hypervbackup.codeplex.com/) to see if the error still occurs.

**Comment by gskoc** [comment]
Ok i've ran the test and these are the results...

.\HyperVBackup.exe -l "VM3" --output "c:\ClusterStorage\Volume4\vmbackups" --compressionlevel 2 1> last_output.log 2> last_error.log

.\HyperVBackup.exe : Error: The requested object was a duplicate.
At line:1 char:1
.\HyperVBackup.exe -l "VM3" --output "c:\ClusterStorage\Volume4\vm ...

CategoryInfo          : NotSpecified: (Error: The requ...as a duplicate.:String) [], RemoteException
FullyQualifiedErrorId : NativeCommandError
 
at Alphaleonis.Win32.Vss.VssBackupComponents.AddToSnapshotSet(String volumeName, Guid providerId)
at HyperVBackUp.Engine.BackupManager.BackupSubset(IDictionary`2 vmNamesMapSubset, Options options)
at HyperVBackUp.Engine.BackupManager.VssBackup(IEnumerable`1 vmNames, VmNameType nameType, Options options)
at HyperVBackup.Console.Program.Main(String[] args)



When i repeat the command i get different error!

.\HyperVBackup.exe : Error: The creation of a shadow copy is already in progress.
At line:1 char:1
.\HyperVBackup.exe -l "VM3" --output "c:\ClusterStorage\Volume4\vm ...

CategoryInfo          : NotSpecified: (Error: The crea...dy in progress.:String) [], RemoteException
FullyQualifiedErrorId : NativeCommandError
 
at Alphaleonis.Win32.Vss.VssBackupComponents.StartSnapshotSet()
at HyperVBackUp.Engine.BackupManager.BackupSubset(IDictionary`2 vmNamesMapSubset, Options options)
at HyperVBackUp.Engine.BackupManager.VssBackup(IEnumerable`1 vmNames, VmNameType n
ameType, Options options)
at HyperVBackup.Console.Program.Main(String[] args)

**Comment by pablopioli** [comment]
Merged the pull request. Will compile a release to made the fix generally available.

**Comment by pablopioli** [comment]
Compiled version 2.2.1 to address this.
Can you confirm it worked for you as expected so I can close this issue?
Thanks

**Comment by gskoc** [comment]
Works like a charm in v2.2.1. Thank you!
