### ISSUE TITLE
.Net 4.8

### ISSUE THREAD

**Issue by tdrusk** [ColiseoSoftware/hypervbackup#21]
Having some issues on a Windows 10 box with .Net 4.8.03752

I'm getting:
```
Copyright (C) 2012 Cloudbase Solutions SRL
Copyright (C) 2016/2017 Coliseo Software SRL

[2020-02-03 16:16:31.1367] Info: HyperVBackup started at 2/3/2020 4:16:31 PM
[2020-02-03 16:16:31.4513] Info: Initializing VSS
Error: Object reference not set to an instance of an object.
   at HyperVBackUp.Engine.BackupManager.BackupSubset(IDictionary`2 vmNamesMapSubset, Options options, ILogger logger)
   at HyperVBackUp.Engine.BackupManager.VssBackup(IEnumerable`1 vmNames, VmNameType nameType, Options options, ILogger logger)
   at HyperVBackup.Console.Program.Main(String[] args)
[2020-02-03 16:16:31.5717] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at HyperVBackUp.Engine.BackupManager.BackupSubset(IDictionary`2 vmNamesMapSubset, Options options, ILogger logger)
   at HyperVBackUp.Engine.BackupManager.VssBackup(IEnumerable`1 vmNames, VmNameType nameType, Options options, ILogger logger)
   at HyperVBackup.Console.Program.Main(String[] args)
```

As far as I know, there is no way to go back to .Net 4.6.1 with Windows 10.

Anything I can do to get this working on Windows 10?

**Comment by eeldivad** [comment]
this code hasn't been updated in 2 years.  checkout https://gallery.technet.microsoft.com/PowerShell-Hyper-V-Backup-7d444752
i haven't tested it yet but it appears to be better maintained

**Comment by tdrusk** [comment]
Cool thanks.

**Comment by pablopioli** [comment]
I have no updated it because I switched to Linux, but for what I know it works even in Windows Server 2019.

As stated in the readme the capabilities to do a hot backup are missing in Windows 10. By MS decission.

You need Windows server to use it.

**Comment by Teravus** [comment]
> this code hasn't been updated in 2 years. checkout https://gallery.technet.microsoft.com/PowerShell-Hyper-V-Backup-7d444752 i haven't tested it yet but it appears to be better maintained

I still use this for backing up individual Linux VMs running on Hyper-V because it does the best job.
