### ISSUE TITLE
Does this work on windows 10 pro? Object Ref not sent to an instance..

### ISSUE THREAD

**Issue by Suvega** [ColiseoSoftware/hypervbackup#9]
With the inclusion of Hyper-V on windows 10, I'm not sure if this tool will work.

(VSS Service is running, Hyper-V service is running, admin command prompt):
Here is the output:

``````
HyperVBackup 2.2
Copyright (C) 2012 Cloudbase Solutions Srl
Copyright (C) 2016 Coliseo Software Srl

Initializing VSS
Error: Object reference not set to an instance of an object.
   at HyperVBackUp.Engine.BackupManager.BackupSubset(IDictionary`2 vmNamesMapSubset, Options options) in P:\VS\Projects\HyperVBackup\HyperVBackup.Engine\BackupManager.cs:line 117
   at HyperVBackUp.Engine.BackupManager.VssBackup(IEnumerable`1 vmNames, VmNameType nameType, Options options) in P:\VS\Projects\HyperVBackup\HyperVBackup.Engine\BackupManager.cs:line 88
   at HyperVBackup.Console.Program.Main(String[] args) in P:\VS\Projects\HyperVBackup\HyperVBackup.Console\Program.cs:line 158```
``````

**Comment by pablopioli** [comment]
No, it won't work.
HyperV in Windows Pro is targeted to developers testings their apps in different environments.
So, it don't include some services targeted to production workloads. One of this is the VSS writer that uses HyperVBackup.
